### ISSUE TITLE
Fix Cancel when Editing Sets

### ISSUE THREAD

**Issue by MisterAkbar** [egrivel/photo-archive#1]
Dropping a quick suggestion -
Could you add a link on the photo editing and the set editing pages that links back to the photo and the photo set respectively? 
This would be helpful particularly helpful when going through sets to fix rotation on individual images as well as when going through years to delete empty sets.

**Comment by egrivel** [comment]
Can you please add details of the intended workflow? For instance, the flow already supported is
 - step through photos using Alt+N keyboard shortcut
 - if a photo is wrong, click Edit
 - make changes in the editor
 - Enter saves and returns to the photo
    - alternatively, Alt+N opens the next photo in the editor

I'd like to know what steps you are envisioning to go through, like do you want to open the link in a new window?

**Comment by MisterAkbar** [comment]
What I'm looking for is a way to back out of the editing window without making changes and go back to to the item being edited. Which when I say it like that the cancel button ought to work for my purposes. Originally I was thinking to go from the edit page directly to the page one "Overview" layer higher than the current item being edited but that saves all of one click and isn't a big deal.

But it's still a valid issue because the cancel button on the set editing doesn't take you back to the set you were editing, instead takes you to cgi-bin/photos-mark/phdisp?imageid=

**Comment by egrivel** [comment]
Renamed this suggestion from "Suggestion - back to archive link in editor" to "Fix Cancel when Editing Sets".

**Comment by egrivel** [comment]
Fixed in commit 531ad756b0266a9a0dd9745e92ce1493c5abe49b
